[package]
name = "quiche-http3-server-unmodified"
version = "0.1.0"
edition = "2021"

[dependencies]
quiche = "0.22"
log = "0.4"
ring = "0.17"
mio = { version = "1.0.3", features = ["net", "os-poll"] }
